services:
  php-cli:
    depends_on:
      mysql:
        condition: service_healthy
        restart: true

  mysql:
    image: mysql:8
    restart: always
    container_name: auditor-mysql
    environment:
      MYSQL_DATABASE: auditor
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_PASSWORD: password
      MYSQL_USER: auditor
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3360:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" , "-u", "auditor", "-ppassword" ]
      timeout: 2s
      retries: 5
      interval: 5s
      start_period: 5s

volumes:
    mysql_data:
